### ISSUE TITLE
[Bug]: Please help, unable to login

### ISSUE THREAD

**Issue by Taratay** [sinamics/ztnet#296]
### 🐛 Describe the Bug

During firt run, when trying to login after registration, logs are flooded with the errors

`[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}`

Unable to login

### 🔍 Steps to Reproduce

I am using Oracle Cloud (ubuntu)

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 📋 ZTNET Logs

```shell
An error occurred while reading the ZT_SECRET
Error: ENOENT: no such file or directory, open '/var/lib/zerotier-one/authtoken.secret'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at /app/.next/server/chunks/9821.js:1:1858
    at /app/.next/server/chunks/9821.js:1:1984 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/lib/zerotier-one/authtoken.secret'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
An error occurred while reading the ZT_SECRET
Error: ENOENT: no such file or directory, open '/var/lib/zerotier-one/authtoken.secret'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at /app/.next/server/chunks/2352.js:1:2350
    at /app/.next/server/chunks/2352.js:1:2476
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/lib/zerotier-one/authtoken.secret'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
[next-auth][error][CLIENT_FETCH_ERROR]
https://next-auth.js.org/errors#client_fetch_error fetch failed {
  error: {
    message: 'fetch failed',
    stack: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11730:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    name: 'TypeError'
  },
  url: 'http://<my ip>:3000/api/auth/session',
  message: 'fetch failed'
}
Socket is initializing
```

**Comment by sinamics** [comment]
Make sure your `NEXTAUTH_URL` is correct in the docker composer file

**Comment by Taratay** [comment]
Hi, thank you for reply, will try

**Comment by Taratay** [comment]
@sinamics mannaged to start service on the local server, the problem presists on oracle VPS it uses internal IP and differenet extrnal IP, seems that affects. I will try to leave localhost as is and proxy it behind nginx.

**Comment by sinamics** [comment]
> the problem presists on oracle VPS it uses internal IP and differenet extrnal IP

you can add `NEXTAUTH_URL_INTERNAL` variable that points to the internal IP, and use `NEXTAUTH_URL` for your external ip.
https://ztnet.network/installation/options#nextauth-configuration
