### ISSUE TITLE
[Support]: Cannot set tags

### ISSUE THREAD

**Issue by eveandcats** [sinamics/ztnet#561]
### 🐛 Describe the Bug

When using the ZTNET API documented [here](https://ztnet.network/Rest%20Api/Personal/Network-Members/modify-a-network-member) to modify a member's tags, it returns `{"fieldErrors": {"": ["Unrecognized key(s) in object: 'tags'"]}, "message": "Validation error"}}`.

### 🔍 Steps to Reproduce

Call
```
curl -L -X POST 'https://<removed>/api/v1/network/<removed>/member/<removed>' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'x-ztnet-auth: <removed>' \
--data-raw '{
  "name": "John Doe",
  "authorized": true,
  "tags":[
      [
        1001,
        2003
      ]
  ]
}'
```

However this is the structure that the tags should be entered in when retrieving the member properties

### 🌐 Browser

Chrome

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### ✨ Expected Behavior

The API request should be accepted

### 📋 ZTNET Logs

```shell
catch cause ZodError: [
  {
    "code": "unrecognized_keys",
    "keys": [
      "tags"
    ],
    "path": [],
    "message": "Unrecognized key(s) in object: 'tags'"
  }
]
    at get error (file:///app/node_modules/zod/lib/index.mjs:538:31)
    at ZodObject.parse (file:///app/node_modules/zod/lib/index.mjs:638:22)
    at /app/.next/server/pages/api/v1/network/[id]/member/[memberId].js:1:3063
    at /app/.next/server/pages/api/v1/network/[id]/member/[memberId].js:1:6631
    at async p (/app/.next/server/pages/api/v1/network/[id]/member/[memberId].js:1:2771)
    at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)
    at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:554:9)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:266:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:791:17)
    at async invokeRender (/app/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/app/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/app/node_modules/next/dist/server/lib/start-server.js:140:13) {
  issues: [
    {
      code: 'unrecognized_keys',
      keys: [Array],
      path: [],
      message: "Unrecognized key(s) in object: 'tags'"
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'unrecognized_keys',
      keys: [Array],
      path: [],
      message: "Unrecognized key(s) in object: 'tags'"
    }
  ]
}
```

**Comment by sinamics** [comment]
This is not a bug. 
Currently the request body only supports `name` and `authorized`
https://ztnet.network/Rest%20Api/Personal/Network-Members/modify-a-network-member

**Comment by eveandcats** [comment]
Ah ok, that makes sense, I missed that section.
